on: [workflow_dispatch]

jobs:
  scanforstring:
    runs-on: ubuntu-latest
    name: Scan for datetime String
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Scan Step
      uses: ericwuehler/ScanForStringAction@master
      id: datetimescan
      with:
        codefolders: './'
        fileextensions: '.md,.sh,.py'
        regex: '.*datetime.*'
        match: 0
        lines: 0
    - name: Get the output
      run: echo "${{ steps.datetimescan.outputs.filelist }}"
