name: Scan for Regex String
on: [workflow_dispatch]
  inputs:
    codefolders:
      description: 'Source code folders to scan, separated by ":"'
      require: true
      default: './'
    fileextensions:
      description: 'File extensions to search for separated by ","'
      require: true
      default: '.c,.java,.py'
    regex:
      description: 'Regex that defines the string to search for'
      require: true
      default: '.*[Cc]opyright.*'
    match:
      description: 'Set this to 1 to search for files that match, 0 for files that do not'
      required: true
      default: 1
    lines:
      description: 'Read the first N lines of the file to find the string, 0 = Entire file'
      require: true
      default: 0
  outputs:
    filelist:
      description: 'The list of files that meet criteria'

jobs:
  scanforstring:
    runs-on: ubuntu-latest
    name: Scan for datetime String
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Scan Step
      uses: ericwuehler/ScanForStringAction@master
      id: datetimescan
      with:
        codefolders: './'
        fileextensions: '.md,.sh,.py'
        regex: '.*datetime.*'
        match: 0
        lines: 0
    - name: Get the output
      run: echo "${{ steps.datetimescan.outputs.filelist }}"
